/* soapH.h
   Generated by gSOAP 2.8.11 from bankaccount.h

Copyright(C) 2000-2012, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under one of the following licenses:
1) GPL or 2) Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#ifndef soapH_H
#define soapH_H
#include "soapStub.h"
#ifndef WITH_NOIDREF

#ifdef __cplusplus
extern "C" {
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_markelement(struct soap*, const void*, int);
SOAP_FMAC3 int SOAP_FMAC4 soap_putelement(struct soap*, const void*, const char*, int, int);
SOAP_FMAC3 void *SOAP_FMAC4 soap_getelement(struct soap*, int*);

#ifdef __cplusplus
}
#endif
SOAP_FMAC3 int SOAP_FMAC4 soap_putindependent(struct soap*);
SOAP_FMAC3 int SOAP_FMAC4 soap_getindependent(struct soap*);
#endif
SOAP_FMAC3 int SOAP_FMAC4 soap_ignore_element(struct soap*);

SOAP_FMAC3 const char ** SOAP_FMAC4 soap_faultcode(struct soap *soap);

SOAP_FMAC3 void * SOAP_FMAC4 soap_instantiate(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 int SOAP_FMAC4 soap_fdelete(struct soap_clist*);
SOAP_FMAC3 void* SOAP_FMAC4 soap_class_id_enter(struct soap*, const char*, void*, int, size_t, const char*, const char*);

#ifndef SOAP_TYPE_byte
#define SOAP_TYPE_byte (3)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_byte(struct soap*, char *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_byte(struct soap*, const char*, int, const char *, const char*);
SOAP_FMAC3 char * SOAP_FMAC4 soap_in_byte(struct soap*, const char*, char *, const char*);

#ifndef soap_write_byte
#define soap_write_byte(soap, data) ( soap_begin_send(soap) || soap_put_byte(soap, data, "byte", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_byte(struct soap*, const char *, const char*, const char*);

#ifndef soap_read_byte
#define soap_read_byte(soap, data) ( soap_begin_recv(soap) || !soap_get_byte(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 char * SOAP_FMAC4 soap_get_byte(struct soap*, char *, const char*, const char*);

#ifndef SOAP_TYPE_int
#define SOAP_TYPE_int (1)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_int(struct soap*, int *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_int(struct soap*, const char*, int, const int *, const char*);
SOAP_FMAC3 int * SOAP_FMAC4 soap_in_int(struct soap*, const char*, int *, const char*);

#ifndef soap_write_int
#define soap_write_int(soap, data) ( soap_begin_send(soap) || soap_put_int(soap, data, "int", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_int(struct soap*, const int *, const char*, const char*);

#ifndef soap_read_int
#define soap_read_int(soap, data) ( soap_begin_recv(soap) || !soap_get_int(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 int * SOAP_FMAC4 soap_get_int(struct soap*, int *, const char*, const char*);

#ifndef SOAP_TYPE_float
#define SOAP_TYPE_float (7)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_float(struct soap*, float *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_float(struct soap*, const char*, int, const float *, const char*);
SOAP_FMAC3 float * SOAP_FMAC4 soap_in_float(struct soap*, const char*, float *, const char*);

#ifndef soap_write_float
#define soap_write_float(soap, data) ( soap_begin_send(soap) || soap_put_float(soap, data, "float", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_float(struct soap*, const float *, const char*, const char*);

#ifndef soap_read_float
#define soap_read_float(soap, data) ( soap_begin_recv(soap) || !soap_get_float(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 float * SOAP_FMAC4 soap_get_float(struct soap*, float *, const char*, const char*);

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Fault
#define SOAP_TYPE_SOAP_ENV__Fault (28)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Fault(struct soap*, const struct SOAP_ENV__Fault *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Fault(struct soap*, const char*, int, const struct SOAP_ENV__Fault *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_in_SOAP_ENV__Fault(struct soap*, const char*, struct SOAP_ENV__Fault *, const char*);

#ifndef soap_write_SOAP_ENV__Fault
#define soap_write_SOAP_ENV__Fault(soap, data) ( soap_begin_send(soap) || (soap_serialize_SOAP_ENV__Fault(soap, data), 0) || soap_put_SOAP_ENV__Fault(soap, data, "SOAP-ENV:Fault", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Fault(struct soap*, const struct SOAP_ENV__Fault *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Fault
#define soap_read_SOAP_ENV__Fault(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Fault(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_get_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *, const char*, const char*);

#define soap_new_SOAP_ENV__Fault(soap, n) soap_instantiate_SOAP_ENV__Fault(soap, n, NULL, NULL, NULL)


#define soap_delete_SOAP_ENV__Fault(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct SOAP_ENV__Fault * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Fault(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Fault(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Reason
#define SOAP_TYPE_SOAP_ENV__Reason (27)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Reason(struct soap*, const struct SOAP_ENV__Reason *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Reason(struct soap*, const char*, int, const struct SOAP_ENV__Reason *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_in_SOAP_ENV__Reason(struct soap*, const char*, struct SOAP_ENV__Reason *, const char*);

#ifndef soap_write_SOAP_ENV__Reason
#define soap_write_SOAP_ENV__Reason(soap, data) ( soap_begin_send(soap) || (soap_serialize_SOAP_ENV__Reason(soap, data), 0) || soap_put_SOAP_ENV__Reason(soap, data, "SOAP-ENV:Reason", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Reason(struct soap*, const struct SOAP_ENV__Reason *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Reason
#define soap_read_SOAP_ENV__Reason(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Reason(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_get_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *, const char*, const char*);

#define soap_new_SOAP_ENV__Reason(soap, n) soap_instantiate_SOAP_ENV__Reason(soap, n, NULL, NULL, NULL)


#define soap_delete_SOAP_ENV__Reason(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct SOAP_ENV__Reason * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Reason(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Reason(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Detail
#define SOAP_TYPE_SOAP_ENV__Detail (24)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Detail(struct soap*, const struct SOAP_ENV__Detail *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Detail(struct soap*, const char*, int, const struct SOAP_ENV__Detail *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_in_SOAP_ENV__Detail(struct soap*, const char*, struct SOAP_ENV__Detail *, const char*);

#ifndef soap_write_SOAP_ENV__Detail
#define soap_write_SOAP_ENV__Detail(soap, data) ( soap_begin_send(soap) || (soap_serialize_SOAP_ENV__Detail(soap, data), 0) || soap_put_SOAP_ENV__Detail(soap, data, "SOAP-ENV:Detail", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Detail(struct soap*, const struct SOAP_ENV__Detail *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Detail
#define soap_read_SOAP_ENV__Detail(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Detail(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_get_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *, const char*, const char*);

#define soap_new_SOAP_ENV__Detail(soap, n) soap_instantiate_SOAP_ENV__Detail(soap, n, NULL, NULL, NULL)


#define soap_delete_SOAP_ENV__Detail(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct SOAP_ENV__Detail * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Detail(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Detail(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Code
#define SOAP_TYPE_SOAP_ENV__Code (22)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Code(struct soap*, const struct SOAP_ENV__Code *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Code(struct soap*, const char*, int, const struct SOAP_ENV__Code *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_in_SOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code *, const char*);

#ifndef soap_write_SOAP_ENV__Code
#define soap_write_SOAP_ENV__Code(soap, data) ( soap_begin_send(soap) || (soap_serialize_SOAP_ENV__Code(soap, data), 0) || soap_put_SOAP_ENV__Code(soap, data, "SOAP-ENV:Code", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Code(struct soap*, const struct SOAP_ENV__Code *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Code
#define soap_read_SOAP_ENV__Code(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Code(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_get_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *, const char*, const char*);

#define soap_new_SOAP_ENV__Code(soap, n) soap_instantiate_SOAP_ENV__Code(soap, n, NULL, NULL, NULL)


#define soap_delete_SOAP_ENV__Code(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct SOAP_ENV__Code * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Code(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Code(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Header
#define SOAP_TYPE_SOAP_ENV__Header (21)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Header(struct soap*, const struct SOAP_ENV__Header *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Header(struct soap*, const char*, int, const struct SOAP_ENV__Header *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_in_SOAP_ENV__Header(struct soap*, const char*, struct SOAP_ENV__Header *, const char*);

#ifndef soap_write_SOAP_ENV__Header
#define soap_write_SOAP_ENV__Header(soap, data) ( soap_begin_send(soap) || (soap_serialize_SOAP_ENV__Header(soap, data), 0) || soap_put_SOAP_ENV__Header(soap, data, "SOAP-ENV:Header", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Header(struct soap*, const struct SOAP_ENV__Header *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Header
#define soap_read_SOAP_ENV__Header(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Header(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_get_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *, const char*, const char*);

#define soap_new_SOAP_ENV__Header(soap, n) soap_instantiate_SOAP_ENV__Header(soap, n, NULL, NULL, NULL)


#define soap_delete_SOAP_ENV__Header(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct SOAP_ENV__Header * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Header(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Header(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef SOAP_TYPE_account1__getAmount
#define SOAP_TYPE_account1__getAmount (20)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_account1__getAmount(struct soap*, struct account1__getAmount *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_account1__getAmount(struct soap*, const struct account1__getAmount *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_account1__getAmount(struct soap*, const char*, int, const struct account1__getAmount *, const char*);
SOAP_FMAC3 struct account1__getAmount * SOAP_FMAC4 soap_in_account1__getAmount(struct soap*, const char*, struct account1__getAmount *, const char*);

#ifndef soap_write_account1__getAmount
#define soap_write_account1__getAmount(soap, data) ( soap_begin_send(soap) || (soap_serialize_account1__getAmount(soap, data), 0) || soap_put_account1__getAmount(soap, data, "account1:getAmount", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_account1__getAmount(struct soap*, const struct account1__getAmount *, const char*, const char*);

#ifndef soap_read_account1__getAmount
#define soap_read_account1__getAmount(soap, data) ( soap_begin_recv(soap) || !soap_get_account1__getAmount(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct account1__getAmount * SOAP_FMAC4 soap_get_account1__getAmount(struct soap*, struct account1__getAmount *, const char*, const char*);

#define soap_new_account1__getAmount(soap, n) soap_instantiate_account1__getAmount(soap, n, NULL, NULL, NULL)


#define soap_delete_account1__getAmount(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct account1__getAmount * SOAP_FMAC2 soap_instantiate_account1__getAmount(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_account1__getAmount(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_account1__getAmountResponse
#define SOAP_TYPE_account1__getAmountResponse (19)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_account1__getAmountResponse(struct soap*, struct account1__getAmountResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_account1__getAmountResponse(struct soap*, const struct account1__getAmountResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_account1__getAmountResponse(struct soap*, const char*, int, const struct account1__getAmountResponse *, const char*);
SOAP_FMAC3 struct account1__getAmountResponse * SOAP_FMAC4 soap_in_account1__getAmountResponse(struct soap*, const char*, struct account1__getAmountResponse *, const char*);

#ifndef soap_write_account1__getAmountResponse
#define soap_write_account1__getAmountResponse(soap, data) ( soap_begin_send(soap) || (soap_serialize_account1__getAmountResponse(soap, data), 0) || soap_put_account1__getAmountResponse(soap, data, "account1:getAmountResponse", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_account1__getAmountResponse(struct soap*, const struct account1__getAmountResponse *, const char*, const char*);

#ifndef soap_read_account1__getAmountResponse
#define soap_read_account1__getAmountResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_account1__getAmountResponse(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct account1__getAmountResponse * SOAP_FMAC4 soap_get_account1__getAmountResponse(struct soap*, struct account1__getAmountResponse *, const char*, const char*);

#define soap_new_account1__getAmountResponse(soap, n) soap_instantiate_account1__getAmountResponse(soap, n, NULL, NULL, NULL)


#define soap_delete_account1__getAmountResponse(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct account1__getAmountResponse * SOAP_FMAC2 soap_instantiate_account1__getAmountResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_account1__getAmountResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_account1__withdrawMoney
#define SOAP_TYPE_account1__withdrawMoney (17)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_account1__withdrawMoney(struct soap*, struct account1__withdrawMoney *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_account1__withdrawMoney(struct soap*, const struct account1__withdrawMoney *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_account1__withdrawMoney(struct soap*, const char*, int, const struct account1__withdrawMoney *, const char*);
SOAP_FMAC3 struct account1__withdrawMoney * SOAP_FMAC4 soap_in_account1__withdrawMoney(struct soap*, const char*, struct account1__withdrawMoney *, const char*);

#ifndef soap_write_account1__withdrawMoney
#define soap_write_account1__withdrawMoney(soap, data) ( soap_begin_send(soap) || (soap_serialize_account1__withdrawMoney(soap, data), 0) || soap_put_account1__withdrawMoney(soap, data, "account1:withdrawMoney", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_account1__withdrawMoney(struct soap*, const struct account1__withdrawMoney *, const char*, const char*);

#ifndef soap_read_account1__withdrawMoney
#define soap_read_account1__withdrawMoney(soap, data) ( soap_begin_recv(soap) || !soap_get_account1__withdrawMoney(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct account1__withdrawMoney * SOAP_FMAC4 soap_get_account1__withdrawMoney(struct soap*, struct account1__withdrawMoney *, const char*, const char*);

#define soap_new_account1__withdrawMoney(soap, n) soap_instantiate_account1__withdrawMoney(soap, n, NULL, NULL, NULL)


#define soap_delete_account1__withdrawMoney(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct account1__withdrawMoney * SOAP_FMAC2 soap_instantiate_account1__withdrawMoney(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_account1__withdrawMoney(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_account1__withdrawMoneyResponse
#define SOAP_TYPE_account1__withdrawMoneyResponse (16)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_account1__withdrawMoneyResponse(struct soap*, struct account1__withdrawMoneyResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_account1__withdrawMoneyResponse(struct soap*, const struct account1__withdrawMoneyResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_account1__withdrawMoneyResponse(struct soap*, const char*, int, const struct account1__withdrawMoneyResponse *, const char*);
SOAP_FMAC3 struct account1__withdrawMoneyResponse * SOAP_FMAC4 soap_in_account1__withdrawMoneyResponse(struct soap*, const char*, struct account1__withdrawMoneyResponse *, const char*);

#ifndef soap_write_account1__withdrawMoneyResponse
#define soap_write_account1__withdrawMoneyResponse(soap, data) ( soap_begin_send(soap) || (soap_serialize_account1__withdrawMoneyResponse(soap, data), 0) || soap_put_account1__withdrawMoneyResponse(soap, data, "account1:withdrawMoneyResponse", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_account1__withdrawMoneyResponse(struct soap*, const struct account1__withdrawMoneyResponse *, const char*, const char*);

#ifndef soap_read_account1__withdrawMoneyResponse
#define soap_read_account1__withdrawMoneyResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_account1__withdrawMoneyResponse(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct account1__withdrawMoneyResponse * SOAP_FMAC4 soap_get_account1__withdrawMoneyResponse(struct soap*, struct account1__withdrawMoneyResponse *, const char*, const char*);

#define soap_new_account1__withdrawMoneyResponse(soap, n) soap_instantiate_account1__withdrawMoneyResponse(soap, n, NULL, NULL, NULL)


#define soap_delete_account1__withdrawMoneyResponse(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct account1__withdrawMoneyResponse * SOAP_FMAC2 soap_instantiate_account1__withdrawMoneyResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_account1__withdrawMoneyResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_account1__addMoney
#define SOAP_TYPE_account1__addMoney (14)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_account1__addMoney(struct soap*, struct account1__addMoney *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_account1__addMoney(struct soap*, const struct account1__addMoney *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_account1__addMoney(struct soap*, const char*, int, const struct account1__addMoney *, const char*);
SOAP_FMAC3 struct account1__addMoney * SOAP_FMAC4 soap_in_account1__addMoney(struct soap*, const char*, struct account1__addMoney *, const char*);

#ifndef soap_write_account1__addMoney
#define soap_write_account1__addMoney(soap, data) ( soap_begin_send(soap) || (soap_serialize_account1__addMoney(soap, data), 0) || soap_put_account1__addMoney(soap, data, "account1:addMoney", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_account1__addMoney(struct soap*, const struct account1__addMoney *, const char*, const char*);

#ifndef soap_read_account1__addMoney
#define soap_read_account1__addMoney(soap, data) ( soap_begin_recv(soap) || !soap_get_account1__addMoney(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct account1__addMoney * SOAP_FMAC4 soap_get_account1__addMoney(struct soap*, struct account1__addMoney *, const char*, const char*);

#define soap_new_account1__addMoney(soap, n) soap_instantiate_account1__addMoney(soap, n, NULL, NULL, NULL)


#define soap_delete_account1__addMoney(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct account1__addMoney * SOAP_FMAC2 soap_instantiate_account1__addMoney(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_account1__addMoney(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_account1__addMoneyResponse
#define SOAP_TYPE_account1__addMoneyResponse (13)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_account1__addMoneyResponse(struct soap*, struct account1__addMoneyResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_account1__addMoneyResponse(struct soap*, const struct account1__addMoneyResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_account1__addMoneyResponse(struct soap*, const char*, int, const struct account1__addMoneyResponse *, const char*);
SOAP_FMAC3 struct account1__addMoneyResponse * SOAP_FMAC4 soap_in_account1__addMoneyResponse(struct soap*, const char*, struct account1__addMoneyResponse *, const char*);

#ifndef soap_write_account1__addMoneyResponse
#define soap_write_account1__addMoneyResponse(soap, data) ( soap_begin_send(soap) || (soap_serialize_account1__addMoneyResponse(soap, data), 0) || soap_put_account1__addMoneyResponse(soap, data, "account1:addMoneyResponse", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_account1__addMoneyResponse(struct soap*, const struct account1__addMoneyResponse *, const char*, const char*);

#ifndef soap_read_account1__addMoneyResponse
#define soap_read_account1__addMoneyResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_account1__addMoneyResponse(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct account1__addMoneyResponse * SOAP_FMAC4 soap_get_account1__addMoneyResponse(struct soap*, struct account1__addMoneyResponse *, const char*, const char*);

#define soap_new_account1__addMoneyResponse(soap, n) soap_instantiate_account1__addMoneyResponse(soap, n, NULL, NULL, NULL)


#define soap_delete_account1__addMoneyResponse(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct account1__addMoneyResponse * SOAP_FMAC2 soap_instantiate_account1__addMoneyResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_account1__addMoneyResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_account1__init
#define SOAP_TYPE_account1__init (11)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_account1__init(struct soap*, struct account1__init *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_account1__init(struct soap*, const struct account1__init *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_account1__init(struct soap*, const char*, int, const struct account1__init *, const char*);
SOAP_FMAC3 struct account1__init * SOAP_FMAC4 soap_in_account1__init(struct soap*, const char*, struct account1__init *, const char*);

#ifndef soap_write_account1__init
#define soap_write_account1__init(soap, data) ( soap_begin_send(soap) || (soap_serialize_account1__init(soap, data), 0) || soap_put_account1__init(soap, data, "account1:init", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_account1__init(struct soap*, const struct account1__init *, const char*, const char*);

#ifndef soap_read_account1__init
#define soap_read_account1__init(soap, data) ( soap_begin_recv(soap) || !soap_get_account1__init(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct account1__init * SOAP_FMAC4 soap_get_account1__init(struct soap*, struct account1__init *, const char*, const char*);

#define soap_new_account1__init(soap, n) soap_instantiate_account1__init(soap, n, NULL, NULL, NULL)


#define soap_delete_account1__init(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct account1__init * SOAP_FMAC2 soap_instantiate_account1__init(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_account1__init(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_account1__initResponse
#define SOAP_TYPE_account1__initResponse (10)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_account1__initResponse(struct soap*, struct account1__initResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_account1__initResponse(struct soap*, const struct account1__initResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_account1__initResponse(struct soap*, const char*, int, const struct account1__initResponse *, const char*);
SOAP_FMAC3 struct account1__initResponse * SOAP_FMAC4 soap_in_account1__initResponse(struct soap*, const char*, struct account1__initResponse *, const char*);

#ifndef soap_write_account1__initResponse
#define soap_write_account1__initResponse(soap, data) ( soap_begin_send(soap) || (soap_serialize_account1__initResponse(soap, data), 0) || soap_put_account1__initResponse(soap, data, "account1:initResponse", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_account1__initResponse(struct soap*, const struct account1__initResponse *, const char*, const char*);

#ifndef soap_read_account1__initResponse
#define soap_read_account1__initResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_account1__initResponse(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct account1__initResponse * SOAP_FMAC4 soap_get_account1__initResponse(struct soap*, struct account1__initResponse *, const char*, const char*);

#define soap_new_account1__initResponse(soap, n) soap_instantiate_account1__initResponse(soap, n, NULL, NULL, NULL)


#define soap_delete_account1__initResponse(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct account1__initResponse * SOAP_FMAC2 soap_instantiate_account1__initResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_account1__initResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Reason
#define SOAP_TYPE_PointerToSOAP_ENV__Reason (30)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Reason(struct soap*, const char *, int, struct SOAP_ENV__Reason *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Reason ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Reason(struct soap*, const char*, struct SOAP_ENV__Reason **, const char*);

#ifndef soap_write_PointerToSOAP_ENV__Reason
#define soap_write_PointerToSOAP_ENV__Reason(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerToSOAP_ENV__Reason(soap, data), 0) || soap_put_PointerToSOAP_ENV__Reason(soap, data, "SOAP-ENV:Reason", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *const*, const char*, const char*);

#ifndef soap_read_PointerToSOAP_ENV__Reason
#define soap_read_PointerToSOAP_ENV__Reason(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerToSOAP_ENV__Reason(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct SOAP_ENV__Reason ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason **, const char*, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Detail
#define SOAP_TYPE_PointerToSOAP_ENV__Detail (29)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Detail(struct soap*, const char *, int, struct SOAP_ENV__Detail *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Detail ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Detail(struct soap*, const char*, struct SOAP_ENV__Detail **, const char*);

#ifndef soap_write_PointerToSOAP_ENV__Detail
#define soap_write_PointerToSOAP_ENV__Detail(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerToSOAP_ENV__Detail(soap, data), 0) || soap_put_PointerToSOAP_ENV__Detail(soap, data, "SOAP-ENV:Detail", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *const*, const char*, const char*);

#ifndef soap_read_PointerToSOAP_ENV__Detail
#define soap_read_PointerToSOAP_ENV__Detail(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerToSOAP_ENV__Detail(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct SOAP_ENV__Detail ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail **, const char*, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Code
#define SOAP_TYPE_PointerToSOAP_ENV__Code (23)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Code(struct soap*, const char *, int, struct SOAP_ENV__Code *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code **, const char*);

#ifndef soap_write_PointerToSOAP_ENV__Code
#define soap_write_PointerToSOAP_ENV__Code(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerToSOAP_ENV__Code(soap, data), 0) || soap_put_PointerToSOAP_ENV__Code(soap, data, "SOAP-ENV:Code", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*, const char*, const char*);

#ifndef soap_read_PointerToSOAP_ENV__Code
#define soap_read_PointerToSOAP_ENV__Code(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerToSOAP_ENV__Code(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code **, const char*, const char*);

#endif

#ifndef SOAP_TYPE_PointerTofloat
#define SOAP_TYPE_PointerTofloat (8)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTofloat(struct soap*, float *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTofloat(struct soap*, const char *, int, float *const*, const char *);
SOAP_FMAC3 float ** SOAP_FMAC4 soap_in_PointerTofloat(struct soap*, const char*, float **, const char*);

#ifndef soap_write_PointerTofloat
#define soap_write_PointerTofloat(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTofloat(soap, data), 0) || soap_put_PointerTofloat(soap, data, "float", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTofloat(struct soap*, float *const*, const char*, const char*);

#ifndef soap_read_PointerTofloat
#define soap_read_PointerTofloat(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTofloat(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 float ** SOAP_FMAC4 soap_get_PointerTofloat(struct soap*, float **, const char*, const char*);

#ifndef SOAP_TYPE__QName
#define SOAP_TYPE__QName (5)
#endif

#define soap_default__QName(soap, a) soap_default_string(soap, a)


#define soap_serialize__QName(soap, a) soap_serialize_string(soap, a)

SOAP_FMAC3 int SOAP_FMAC4 soap_out__QName(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in__QName(struct soap*, const char*, char **, const char*);

#ifndef soap_write__QName
#define soap_write__QName(soap, data) ( soap_begin_send(soap) || (soap_serialize__QName(soap, data), 0) || soap_put__QName(soap, data, "byte", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put__QName(struct soap*, char *const*, const char*, const char*);

#ifndef soap_read__QName
#define soap_read__QName(soap, data) ( soap_begin_recv(soap) || !soap_get__QName(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 char ** SOAP_FMAC4 soap_get__QName(struct soap*, char **, const char*, const char*);

#ifndef SOAP_TYPE_string
#define SOAP_TYPE_string (4)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_string(struct soap*, char **);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_string(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_string(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in_string(struct soap*, const char*, char **, const char*);

#ifndef soap_write_string
#define soap_write_string(soap, data) ( soap_begin_send(soap) || (soap_serialize_string(soap, data), 0) || soap_put_string(soap, data, "byte", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_string(struct soap*, char *const*, const char*, const char*);

#ifndef soap_read_string
#define soap_read_string(soap, data) ( soap_begin_recv(soap) || !soap_get_string(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 char ** SOAP_FMAC4 soap_get_string(struct soap*, char **, const char*, const char*);

#endif

/* End of soapH.h */
