/* soapClient.c
   Generated by gSOAP 2.8.11 from bankaccount.h

Copyright(C) 2000-2012, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under one of the following licenses:
1) GPL or 2) Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#if defined(__BORLANDC__)
#pragma option push -w-8060
#pragma option push -w-8004
#endif
#include "soapH.h"
#ifdef __cplusplus
extern "C" {
#endif

SOAP_SOURCE_STAMP("@(#) soapClient.c ver 2.8.11 2012-11-28 02:13:11 GMT")


SOAP_FMAC5 int SOAP_FMAC6 soap_call_account1__init(struct soap *soap, const char *soap_endpoint, const char *soap_action, float amount, float *result)
{	struct account1__init soap_tmp_account1__init;
	struct account1__initResponse *soap_tmp_account1__initResponse;
	soap->encodingStyle = NULL;
	soap_tmp_account1__init.amount = amount;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_account1__init(soap, &soap_tmp_account1__init);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_account1__init(soap, &soap_tmp_account1__init, "account1:init", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_account1__init(soap, &soap_tmp_account1__init, "account1:init", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!result)
		return soap_closesock(soap);
	soap_default_float(soap, result);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_tmp_account1__initResponse = soap_get_account1__initResponse(soap, NULL, "account1:initResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	if (result && soap_tmp_account1__initResponse->result)
		*result = *soap_tmp_account1__initResponse->result;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_account1__addMoney(struct soap *soap, const char *soap_endpoint, const char *soap_action, float amount, float *result)
{	struct account1__addMoney soap_tmp_account1__addMoney;
	struct account1__addMoneyResponse *soap_tmp_account1__addMoneyResponse;
	soap->encodingStyle = NULL;
	soap_tmp_account1__addMoney.amount = amount;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_account1__addMoney(soap, &soap_tmp_account1__addMoney);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_account1__addMoney(soap, &soap_tmp_account1__addMoney, "account1:addMoney", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_account1__addMoney(soap, &soap_tmp_account1__addMoney, "account1:addMoney", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!result)
		return soap_closesock(soap);
	soap_default_float(soap, result);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_tmp_account1__addMoneyResponse = soap_get_account1__addMoneyResponse(soap, NULL, "account1:addMoneyResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	if (result && soap_tmp_account1__addMoneyResponse->result)
		*result = *soap_tmp_account1__addMoneyResponse->result;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_account1__withdrawMoney(struct soap *soap, const char *soap_endpoint, const char *soap_action, float amount, float *result)
{	struct account1__withdrawMoney soap_tmp_account1__withdrawMoney;
	struct account1__withdrawMoneyResponse *soap_tmp_account1__withdrawMoneyResponse;
	soap->encodingStyle = NULL;
	soap_tmp_account1__withdrawMoney.amount = amount;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_account1__withdrawMoney(soap, &soap_tmp_account1__withdrawMoney);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_account1__withdrawMoney(soap, &soap_tmp_account1__withdrawMoney, "account1:withdrawMoney", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_account1__withdrawMoney(soap, &soap_tmp_account1__withdrawMoney, "account1:withdrawMoney", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!result)
		return soap_closesock(soap);
	soap_default_float(soap, result);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_tmp_account1__withdrawMoneyResponse = soap_get_account1__withdrawMoneyResponse(soap, NULL, "account1:withdrawMoneyResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	if (result && soap_tmp_account1__withdrawMoneyResponse->result)
		*result = *soap_tmp_account1__withdrawMoneyResponse->result;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_account1__getAmount(struct soap *soap, const char *soap_endpoint, const char *soap_action, float *result)
{	struct account1__getAmount soap_tmp_account1__getAmount;
	struct account1__getAmountResponse *soap_tmp_account1__getAmountResponse;
	soap->encodingStyle = NULL;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_account1__getAmount(soap, &soap_tmp_account1__getAmount);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_account1__getAmount(soap, &soap_tmp_account1__getAmount, "account1:getAmount", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_account1__getAmount(soap, &soap_tmp_account1__getAmount, "account1:getAmount", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!result)
		return soap_closesock(soap);
	soap_default_float(soap, result);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_tmp_account1__getAmountResponse = soap_get_account1__getAmountResponse(soap, NULL, "account1:getAmountResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	if (result && soap_tmp_account1__getAmountResponse->result)
		*result = *soap_tmp_account1__getAmountResponse->result;
	return soap_closesock(soap);
}

#ifdef __cplusplus
}
#endif

#if defined(__BORLANDC__)
#pragma option pop
#pragma option pop
#endif

/* End of soapClient.c */
